const Types = {
  SET_COLOURS: 'SET_COLOURS',
  MOVE_SEED_TO_POSITION: 'MOVE_SEED_TO_POSITION',
  UPDATE_BOARD_SETTINGS: 'UPDATE_BOARD_SETTINGS',
  DISABLE_INACTIVE_HOUSE_SEEDS: 'DISABLE_INACTIVE_HOUSE_SEEDS',
  DIE_CAST_COMPLETE: 'DIE_CAST_COMPLETE',
  SET_SELECTED_SEED: 'SET_SELECTED_SEED',
  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
  CREATE_NOTIFICATION: 'CREATE_NOTIFICATION',
  CHANGE_TURN: 'CHANGE_TURN',
  NUMBER_OF_PLAYERS: 'NUMBER_OF_PLAYERS',
  SET_DISABLED_HOUSES: 'SET_DISABLED_HOUSES',
  NUMBER_OF_PLAYERS_UPDATED: 'NUMBER_OF_PLAYERS_UPDATED',
  SET_DISABLED_HOUSES_COMPLETE: 'SET_DISABLED_HOUSES_COMPLETE',
  REMOVE_PLAYER_FROM_LIST: 'REMOVE_PLAYER_FROM_LIST',
  SET_RESULT_TO_GLOBAL: 'SET_RESULT_TO_GLOBAL',
  RESET_GAME_DATA: 'RESET_GAME_DATA',
};

export default Types;