const Types = {
  SET_COLOURS: 'SET_COLOURS',
  MOVE_SEED_TO_POSITION: 'MOVE_SEED_TO_POSITION',
  UPDATE_BOARD_SETTINGS: 'UPDATE_BOARD_SETTINGS',
  DISABLE_INACTIVE_HOUSE_SEEDS: 'DISABLE_INACTIVE_HOUSE_SEEDS',
  DIE_CAST_COMPLETE: 'DIE_CAST_COMPLETE',
  SET_SELECTED_SEED: 'SET_SELECTED_SEED',
};

export default Types;